config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, :path => 'auth', controllers: {
  #   registrations: 'devise/registrations'
  #   }
  devise_for :users, :path => 'auth', controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users#, only: [:index]

  devise_scope :user do
    root to: "users/registrations#edit"
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  def full_address
    str = self.line_1
    ['line_2', 'landmark', 'pincode', 'city', 'state', 'country'].each do |attrr|
      str += ", #{self.try(attrr)}" if self.try(attrr).present?
    end
    str
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:user, :admin]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :address, dependent: :destroy, autosave: true

  validates :name, :presence => true
  validates :email,
            :uniqueness => {:message => "Another account is already using this email address"},
            :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
            :message=> "Invalid Email Id" },
            :presence =>true

  has_one_attached :profile_picture
  accepts_nested_attributes_for :address

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def full_address
    self.address.try(:full_address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :profile_picture, :address_attributes=> [:line_1, :line_2, :landmark, :pincode, :city, :state]] )
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_picture, :address_attributes=> [:id, :line_1, :line_2, :city, :state, :pincode, :landmark]])
  # end

  def after_sign_in_path_for(resource)
    if resource.present? && resource.admin?
      users_path
    else
      root_path
    end
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  def new
    #super
    build_resource({})
    resource.build_address
    respond_with self.resource
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    authorize current_user
    super
  end

  # PUT /resource
  def update
    authorize current_user
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      added_attrs = [:name, :email, :profile_picture, :password, :password_confirmation, :remember_me, :address_attributes=> [:line_1, :line_2, :city, :state, :pincode, :landmark, :country, :mobile_number]]
      devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    end

  # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      if current_user.admin?
        added_attrs = [:address_attributes=> [:id, :mobile_number]]
      else
        added_attrs = [:name, :profile_picture, :address_attributes=> [:id, :line_1, :line_2, :city, :state, :pincode, :landmark, :country, :mobile_number]]
      end
      devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
    end

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
  private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_admin
  before_action :set_user, only: [:edit, :update]
  after_action :verify_authorized

  def index
    authorize User
    @users = User.user.order('id desc').with_attached_profile_picture
    @users = @users.paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_update_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
    def user_update_params
      params.require(:user).permit(policy(User).permitted_attributes)
    end

    def set_user
      @user = User.where(id: params[:id]).first
    end

    def verify_admin
      redirect_to '/' unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_formatter(date)
    date.to_date.strftime('%b %d %Y') rescue ''
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-sm.bg-light.navbar-light
  ul.navbar-nav
    - if user_signed_in?
      li.nav-item
        = link_to "Sign out", destroy_user_session_path, method: :get, class: "nav-link"
      - unless params[:controller] == 'users/registrations'
        li.nav-item
          = link_to "Edit Profile", edit_user_registration_path, class: "nav-link"
      - if current_user.admin?
        li.nav-item
          = link_to "Users", users_path, class: "nav-link"
    - else
      - if params[:controller] != 'users/registrations'
        li class = "#{(params[:controller] == 'users/registrations' ? 'nav-item active' : 'nav-item')}" 
          = link_to "Sign up", new_user_registration_path, class: "nav-link"
      - if params[:controller] != 'devise/sessions'
        li class = "#{(params[:controller] == 'devise/sessions' ? 'nav-item active' : 'nav-item')}"
          = link_to "Sign in", new_user_session_path, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title SolbegAssignment
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
  body
    .container
      = render '/layouts/header'
      #page-wrapper
        - flash.each do |type, msg|
          p class=("alert alert-#{type == 'error' ? 'danger' : 'success'} alert-dismissable") = msg
        = yield

app/views/users/edit.html.erb
<div class="container bootstrap snippet">
  <%= form_for(@user, url: user_path(@user), html: { method: :put, class: "form" }) do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>
    <br>
    <%- admin = f.object.admin? %>
    <div class="row">
      <div class="col-sm-3"><!--left col-->
        <div class="text-center">
          <% if @user.profile_picture.attached?%>
            <%= image_tag @user.profile_picture , class: "avatar img-circle img-thumbnail", alt: "avatar" %>
          <% end%>
          <% unless admin %>
            <%= f.file_field :profile_picture, class: "text-center center-block file-upload" %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="tab-content">
          <div class="tab-pane active" id="home">
            <div class="form-label-group">
              <%= f.text_field :name, class: 'form-control', readonly: true %>

              <%= f.label :name  %>
            </div>
            <div class="form-label-group">
              <%= f.text_field :email, class: 'form-control', readonly: true %>
              <%= f.label :email  %>
            </div>
            
            <%= render partial: "devise/registrations/address_fields", locals: {resource_frm: f} %>
            <div class="form-group">
              <div class="col-xs-12">
                <%= f.submit "Save", class: 'btn btn-lg btn-success' %>
              </div>
            </div>
            
            
          </div><!--/tab-pane-->
        </div><!--/tab-content-->
      </div><!--/col-9-->
    </div><!--/row-->
  <% end %>
  </div>                                                    

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-12 mx-auto">
    <div class="card card-signin my-5">
      <div class="card-body">
        <h5 class="card-title text-center">Users Listing</h5>
        <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th class="th-sm">Name

              </th>
              <th class="th-sm">Email

              </th>
              <th class="th-sm">Address

              </th>
              <th class="th-sm">Profile Picture

              </th>
              <th class="th-sm">Registered date

              </th>
              <th class="th-sm">Actions

              </th>
            </tr>
          </thead>
          <tbody>
            <%- @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.full_address %></td>
                <td>
                  <% if user.profile_picture.attached? %>
                    <%= image_tag user.profile_picture.variant(resize_to_limit: [100, 100])%>
                  <% end %>
                </td>
                <td><%= date_formatter(user.created_at) %></td>
                <td>
                  <%= link_to "Edit", edit_user_path(user), class: "nav-link" %>
                </td>
              </tr>
            <% end %>
          </tbody>
          <% if @user.present? %>
            <tfoot>
              <tr>
                <th>Name
                </th>
                <th>Email
                </th>
                <th>Gender
                </th>
                <th>Age
                </th>
                <th>Country
                </th>
                <th>Registered Date
                </th>
              </tr>
            </tfoot>
            <% end %>
        </table>
        <%= will_paginate @users %>
      </div>
    </div>
  </div>
</div>